# -*- coding: utf-8 -*-
"""papaDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFiYDTB0QLmaMSbObiSwUyPyhboq2a-E
"""

!pip install -q ultralytics pycocotools tqdm

!wget -q http://images.cocodataset.org/zips/val2017.zip
!wget -q http://images.cocodataset.org/annotations/annotations_trainval2017.zip

!unzip -q val2017.zip
!unzip -q annotations_trainval2017.zip

import os
import shutil
from pycocotools.coco import COCO

ann_file = "/content/annotations/instances_val2017.json"
coco = COCO(ann_file)

# COCO category IDs
target_classes = {
    1: 0,    # person -> YOLO class 0
    16: 1,   # bird -> YOLO class 1
    18: 2    # dog -> YOLO class 2
}

os.makedirs("/content/dataset/images", exist_ok=True)
os.makedirs("/content/dataset/labels", exist_ok=True)

img_ids = set()

for cat_id in target_classes:
    ids = coco.getImgIds(catIds=[cat_id])[:50]
    img_ids.update(ids)

print("Images found:", len(img_ids))

from tqdm import tqdm

for img_id in tqdm(img_ids):
    img = coco.loadImgs(img_id)[0]

    src = f"/content/val2017/{img['file_name']}"
    dst = f"/content/dataset/images/{img['file_name']}"

    if not os.path.exists(src):
        continue

    shutil.copy(src, dst)

    ann_ids = coco.getAnnIds(imgIds=img_id)
    anns = coco.loadAnns(ann_ids)

    label_file = dst.replace("/images/", "/labels/")
    label_file = label_file.replace(".jpg", ".txt")

    lines = []

    for ann in anns:
        cat = ann["category_id"]

        if cat not in target_classes:
            continue

        x, y, w, h = ann["bbox"]

        img_w = img["width"]
        img_h = img["height"]

        x_center = (x + w/2) / img_w
        y_center = (y + h/2) / img_h

        w /= img_w
        h /= img_h

        cls = target_classes[cat]

        lines.append(
            f"{cls} {x_center} {y_center} {w} {h}"
        )

    with open(label_file, "w") as f:
        f.write("\n".join(lines))

import random

images = os.listdir("/content/dataset/images")
random.shuffle(images)

split = int(0.8 * len(images))

train_imgs = images[:split]
valid_imgs = images[split:]

for folder in [
    "train/images",
    "train/labels",
    "valid/images",
    "valid/labels"
]:
    os.makedirs(f"/content/dataset/{folder}", exist_ok=True)

for img in train_imgs:
    shutil.move(
        f"/content/dataset/images/{img}",
        f"/content/dataset/train/images/{img}"
    )

    shutil.move(
        f"/content/dataset/labels/{img.replace('.jpg','.txt')}",
        f"/content/dataset/train/labels/{img.replace('.jpg','.txt')}"
    )

for img in valid_imgs:
    shutil.move(
        f"/content/dataset/images/{img}",
        f"/content/dataset/valid/images/{img}"
    )

    shutil.move(
        f"/content/dataset/labels/{img.replace('.jpg','.txt')}",
        f"/content/dataset/valid/labels/{img.replace('.jpg','.txt')}"
    )

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset/data.yaml
# path: /content/dataset
# 
# train: train/images
# val: valid/images
# 
# names:
#   0: person
#   1: bird
#   2: dog

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/dataset/data.yaml",
    epochs=10,
    imgsz=416,
    batch=4,
    device="cpu"
)

model = YOLO("runs/detect/train/weights/best.pt")

results = model.predict(
    source="/content/test.jpg",
    conf=0.25
)

import cv2
import matplotlib.pyplot as plt

for r in results:
    img = cv2.cvtColor(r.plot(), cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10,10))
    plt.imshow(img)
    plt.axis("off")
    plt.show()